// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB6oLZf_y6Kdn2s0CZCWjY6HGBMr2xugw',
    appId: '1:122613859782:web:7b6fb868b4686aa0291ec7',
    messagingSenderId: '122613859782',
    projectId: 'tantrafiesta-6052b',
    authDomain: 'tantrafiesta-6052b.firebaseapp.com',
    storageBucket: 'tantrafiesta-6052b.appspot.com',
    measurementId: 'G-86F4DCXBR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK30uohdYv8jZei6OSJdWn_Q9_7-nHKzw',
    appId: '1:122613859782:android:af79499683b2c385291ec7',
    messagingSenderId: '122613859782',
    projectId: 'tantrafiesta-6052b',
    storageBucket: 'tantrafiesta-6052b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4fpmf-vfycUiWeyeRpCdj6MdmfRE7VHM',
    appId: '1:122613859782:ios:dbc4c687518d6ca5291ec7',
    messagingSenderId: '122613859782',
    projectId: 'tantrafiesta-6052b',
    storageBucket: 'tantrafiesta-6052b.appspot.com',
    androidClientId: '122613859782-qcura6iecvqqrtlt87chg62pbl8l91c9.apps.googleusercontent.com',
    iosClientId: '122613859782-9a4m8v44ud4km442dmvl9di8rll43b64.apps.googleusercontent.com',
    iosBundleId: 'com.example.rPlaceClone',
  );
}